name: Clang Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clang compiler installation
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt upgrade
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 14

      - name: Example 1 Build
        run: |
          clang -x c -E -include src/wtfc.wtfch -o expressions_prep.c examples/expressions.wtfc
          clang -w -o expressions expressions_prep.c
          rm expressions_prep.c

      - name: Example 2 Build
        run: |
          clang -x c -E -include src/wtfc.wtfch -o full_example_prep.c examples/full_example.wtfc
          clang -w -o full_example full_example_prep.c
          rm full_example_prep.c
